[package]
name = "webgame"
version = "0.1.0"
authors = ["Paul Warner <paul.eliot.warner@gmail.com>"]

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rusqlite = "0.14.0"

[dependencies.rocket_contrib]
version = "0.3.16"
default-features = false
features = ["tera_templates"]